-- begin CONTENEDORES
create unique index IDX_CONTENEDORES_UK_TAG_ID on CONTENEDORES (TAG_ID) where DELETE_TS is null ^
create unique index IDX_CONTENEDORES_UK_CONTENEDOR on CONTENEDORES (CONTENEDOR) where DELETE_TS is null ^
-- end CONTENEDORES
-- begin VITRONTRACK_VARIEDADES
create unique index IDX_VITRONTRACK_VARIEDADES_UK_VARIEDAD on VITRONTRACK_VARIEDADES (VARIEDAD) where DELETE_TS is null ^
-- end VITRONTRACK_VARIEDADES
-- begin VITRONTRACK_MULTIPLICACIONES
alter table VITRONTRACK_MULTIPLICACIONES add constraint FK_VITRONTRACK_MULTIPLICACIONES_ON_ID_PADRE foreign key (ID_PADRE_ID) references VITRONTRACK_MULTIPLICACIONES(ID)^
create unique index IDX_VITRONTRACK_MULTIPLICACIONES_UK_MULTIPLICACION on VITRONTRACK_MULTIPLICACIONES (MULTIPLICACION) where DELETE_TS is null ^
create index IDX_VITRONTRACK_MULTIPLICACIONES_ON_ID_PADRE on VITRONTRACK_MULTIPLICACIONES (ID_PADRE_ID)^
-- end VITRONTRACK_MULTIPLICACIONES
-- begin VITRONTRACK_PRODUCCIONES
alter table VITRONTRACK_PRODUCCIONES add constraint FK_VITRONTRACK_PRODUCCIONES_ON_CONTENEDOR foreign key (CONTENEDOR_ID) references CONTENEDORES(ID)^
alter table VITRONTRACK_PRODUCCIONES add constraint FK_VITRONTRACK_PRODUCCIONES_ON_VARIEDAD foreign key (VARIEDAD_ID) references VITRONTRACK_VARIEDADES(ID)^
alter table VITRONTRACK_PRODUCCIONES add constraint FK_VITRONTRACK_PRODUCCIONES_ON_MULTIPLICACION foreign key (MULTIPLICACION_ID) references VITRONTRACK_MULTIPLICACIONES(ID)^
alter table VITRONTRACK_PRODUCCIONES add constraint FK_VITRONTRACK_PRODUCCIONES_ON_MEDIOS foreign key (MEDIOS_ID) references VITRONTRACK_MEDIOS(ID)^
create index IDX_VITRONTRACK_PRODUCCIONES_ON_CONTENEDOR on VITRONTRACK_PRODUCCIONES (CONTENEDOR_ID)^
create index IDX_VITRONTRACK_PRODUCCIONES_ON_VARIEDAD on VITRONTRACK_PRODUCCIONES (VARIEDAD_ID)^
create index IDX_VITRONTRACK_PRODUCCIONES_ON_MULTIPLICACION on VITRONTRACK_PRODUCCIONES (MULTIPLICACION_ID)^
create index IDX_VITRONTRACK_PRODUCCIONES_ON_MEDIOS on VITRONTRACK_PRODUCCIONES (MEDIOS_ID)^
-- end VITRONTRACK_PRODUCCIONES
-- begin VITRONTRACK_MEDIOS
create unique index IDX_VITRONTRACK_MEDIOS_UK_MEDIO on VITRONTRACK_MEDIOS (MEDIO) where DELETE_TS is null ^
-- end VITRONTRACK_MEDIOS
